project:
  type: website

website:
  title: "sebffischer.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sebffischer
format:
  html:
    theme: cosmo
    css: styles.css

execute: 
  freeze: auto
